// Sample data for demo purposes – realistic Hungarian window/door examples

import { nanoid } from "nanoid";
import type { AjanlatAdatok } from "./types";

export const MINTA_CSALADI_HAZ: AjanlatAdatok = {
  ugyfel: {
    nev: "Kovács István",
    telefon: "+36 30 123 4567",
    email: "kovacs.istvan@email.hu",
    helyszin: "1234 Budapest, Rózsa utca 12.",
    megjegyzes: "Felújítás, régi fa ablakok cseréje",
  },
  projekt: {
    nev: "Kovács - Rózsa utca felújítás",
    kapcsolatTipus: "felmeres",
    hataridoSurgosseg: "2024. március vége",
    belsomegjegyzes: "Ügyfél sürgős, tavaszi beépítést szeretne",
  },
  tetelek: [
    {
      id: nanoid(),
      kategoria: "ablak",
      profilRendszer: "Rehau",
      szelesseg: "120",
      magassag: "150",
      darabszam: "4",
      nyitasMod: "bukonyilo",
      nyitasIrany: "jobb",
      szin: "Fehér",
      uvegezés: "3_retegu",
      parkany: true,
      redony: true,
      szunyoghalo: true,
      egyebKiegeszitok: "",
      belsomegjegyzes: "Nappali + hálók ablakai",
    },
    {
      id: nanoid(),
      kategoria: "ablak",
      profilRendszer: "Rehau",
      szelesseg: "60",
      magassag: "90",
      darabszam: "2",
      nyitasMod: "bukonyilo",
      nyitasIrany: "bal",
      szin: "Fehér",
      uvegezés: "3_retegu",
      parkany: true,
      redony: false,
      szunyoghalo: true,
      egyebKiegeszitok: "",
      belsomegjegyzes: "Fürdőszoba + WC",
    },
    {
      id: nanoid(),
      kategoria: "erkelyajto",
      profilRendszer: "Rehau",
      szelesseg: "90",
      magassag: "210",
      darabszam: "1",
      nyitasMod: "bukonyilo",
      nyitasIrany: "bal",
      szin: "Fehér",
      uvegezés: "3_retegu",
      parkany: false,
      redony: true,
      szunyoghalo: true,
      egyebKiegeszitok: "",
      belsomegjegyzes: "Teraszra nyíló erkélyajtó",
    },
    {
      id: nanoid(),
      kategoria: "bejárati_ajto",
      profilRendszer: "Rehau",
      szelesseg: "100",
      magassag: "210",
      darabszam: "1",
      nyitasMod: "nyilo",
      nyitasIrany: "bal",
      szin: "Antracit",
      uvegezés: "biztonsagi",
      parkany: false,
      redony: false,
      szunyoghalo: false,
      egyebKiegeszitok: "Biztonsági zár, szemlélőlyuk",
      belsomegjegyzes: "Főbejárat",
    },
  ],
  statusz: "ellenorzesre_var",
  letrehozva: new Date().toISOString(),
  modositva: new Date().toISOString(),
};

export const MINTA_ERKELYAJTO: AjanlatAdatok = {
  ugyfel: {
    nev: "Nagy Éva",
    telefon: "+36 20 987 6543",
    email: "nagy.eva@gmail.com",
    helyszin: "9700 Szombathely, Kossuth tér 5. 3/8.",
    megjegyzes: "Panellakás, erkélyre nyíló ajtó csere",
  },
  projekt: {
    nev: "Nagy - erkélyajtó csere",
    kapcsolatTipus: "bejovo_erdeklodes",
    hataridoSurgosseg: "Rugalmas",
    belsomegjegyzes: "Telefonon egyeztettünk, helyszíni felmérés szükséges",
  },
  tetelek: [
    {
      id: nanoid(),
      kategoria: "erkelyajto",
      profilRendszer: "Gealan",
      szelesseg: "90",
      magassag: "215",
      darabszam: "1",
      nyitasMod: "bukonyilo",
      nyitasIrany: "jobb",
      szin: "Fehér",
      uvegezés: "3_retegu",
      parkany: false,
      redony: false,
      szunyoghalo: true,
      egyebKiegeszitok: "Szúnyogháló ajtó is kell",
      belsomegjegyzes: "Panel méret, pontos mérés szükséges",
    },
  ],
  statusz: "piszkazat",
  letrehozva: new Date().toISOString(),
  modositva: new Date().toISOString(),
};

export const MINTA_BEJÁRATI_AJTO: AjanlatAdatok = {
  ugyfel: {
    nev: "Tóth Péter",
    telefon: "+36 70 555 1234",
    email: "toth.peter@ceg.hu",
    helyszin: "4025 Debrecen, Piac utca 88.",
    megjegyzes: "Irodaépület bejárata, biztonsági igény",
  },
  projekt: {
    nev: "Tóth - irodaépület bejárat",
    kapcsolatTipus: "meglevo_ugyfel",
    hataridoSurgosseg: "2024. február",
    belsomegjegyzes: "Meglévő ügyfél, kedvezmény lehetséges",
  },
  tetelek: [
    {
      id: nanoid(),
      kategoria: "bejárati_ajto",
      profilRendszer: "Rehau",
      szelesseg: "120",
      magassag: "220",
      darabszam: "1",
      nyitasMod: "nyilo",
      nyitasIrany: "jobb",
      szin: "Antracit",
      uvegezés: "biztonsagi",
      parkany: false,
      redony: false,
      szunyoghalo: false,
      egyebKiegeszitok: "Elektromos zár, kódos nyitás, könyöklő",
      belsomegjegyzes: "RC3 biztonsági osztály kell",
    },
    {
      id: nanoid(),
      kategoria: "ablak",
      profilRendszer: "Rehau",
      szelesseg: "80",
      magassag: "120",
      darabszam: "3",
      nyitasMod: "bukonyilo",
      nyitasIrany: "jobb",
      szin: "Antracit",
      uvegezés: "3_retegu",
      parkany: false,
      redony: false,
      szunyoghalo: false,
      egyebKiegeszitok: "",
      belsomegjegyzes: "Irodai ablakok, egységes szín a bejárattal",
    },
  ],
  statusz: "piszkazat",
  letrehozva: new Date().toISOString(),
  modositva: new Date().toISOString(),
};
